---
title: The Effective Fly Box
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ""
    type: "posts"
  values:
    footer-extra: disclaimer.html
  - scope:
    path: ""
    type: "pages"
  values:
    footer-extra: disclaimer.html  
permalink: "/:categories/:title.html"
url: https://www.effectiveflybox.com
author: Greg Monigold
google_analytics_code: 
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
- jekyll-remote-theme
paginate: 5
navbar-links:
  Begin: a-path
  Tying: tags#effective
  Patterns: tags#patterns
  Materials: materialTagsGreg Monigold  •  2026
  Tools: tags#tools
  Why: why
excerpt_length: 50
