---
title: The Effective Fly Box
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title.html"
url: https://www.effectiveflybox.com
author: Greg Monigold
copyright_year: 2025
google_analytics_code: 
aboutme: 100% human generated, poorly worded content that should never be considered
  to be in a final state.
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
- jekyll-remote-theme
paginate: 5
navbar-links:
  Begin: a-path
  Tying: tags#effective
  Patterns: tags#patterns
  Materials: materialTags
  Tools: tags#tools
  Who Did This?: who-did-this
excerpt_length: 50
